databases:
  - name: budget_app_db
    databaseName: budget_app_db_ln2k
    user: budget_app
    region: singapore

services:
  - type: web
    name: budget_app
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budget_app_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false